//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiReader.SharpEpub {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiReader.SharpEpub.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/oebps-package+xml.
        /// </summary>
        internal static string ContainerMediaType {
            get {
                return ResourceManager.GetString("ContainerMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urn:oasis:names:tc:opendocument:xmlns:container.
        /// </summary>
        internal static string ContainerNs {
            get {
                return ResourceManager.GetString("ContainerNs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/xhtml+xml.
        /// </summary>
        internal static string ContentMediaType {
            get {
                return ResourceManager.GetString("ContentMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.xml;*.*htm*;.
        /// </summary>
        internal static string ContentPatterns {
            get {
                return ResourceManager.GetString("ContentPatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/css.
        /// </summary>
        internal static string CssMediaType {
            get {
                return ResourceManager.GetString("CssMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urn:uuid:.
        /// </summary>
        internal static string IdentifierPrefix {
            get {
                return ResourceManager.GetString("IdentifierPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.jpg;*.jpeg;*.gif;*.png;*.bmp;*.tiff;.
        /// </summary>
        internal static string ImagePatterns {
            get {
                return ResourceManager.GetString("ImagePatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://purl.org/dc/elements/1.1/.
        /// </summary>
        internal static string MetadataXmlnsDc {
            get {
                return ResourceManager.GetString("MetadataXmlnsDc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.idpf.org/2007/opf.
        /// </summary>
        internal static string MetadataXmlnsOpf {
            get {
                return ResourceManager.GetString("MetadataXmlnsOpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/epub+zip.
        /// </summary>
        internal static string Mimetype {
            get {
                return ResourceManager.GetString("Mimetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-dtbncx+xml.
        /// </summary>
        internal static string NcxMediaType {
            get {
                return ResourceManager.GetString("NcxMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.daisy.org/z3986/2005/ncx/.
        /// </summary>
        internal static string NcxNs {
            get {
                return ResourceManager.GetString("NcxNs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2005-1.
        /// </summary>
        internal static string NcxVersion {
            get {
                return ResourceManager.GetString("NcxVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to epub-publication.
        /// </summary>
        internal static string OpfEvent {
            get {
                return ResourceManager.GetString("OpfEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPB-UUID.
        /// </summary>
        internal static string OpfIdentifierField {
            get {
                return ResourceManager.GetString("OpfIdentifierField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.idpf.org/2007/opf.
        /// </summary>
        internal static string OpfPackageNs {
            get {
                return ResourceManager.GetString("OpfPackageNs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aut.
        /// </summary>
        internal static string OpfRole {
            get {
                return ResourceManager.GetString("OpfRole", resourceCulture);
            }
        }
    }
}
